### ISSUE TITLE
Cmake a required dependency on osx

### ISSUE THREAD

**Issue by pzelnip** [jankrepl/pychubby#11]
Doing pip install pychubby on a OSX machine (Sierra, 10.12.6) with Python 3.7 gives:

```
$ pip install pychubby
Collecting pychubby
  Downloading https://files.pythonhosted.org/packages/c3/09/5c9dd0c6c6b097118327d1a2f7a163bafc4d80269c102f3e036cb8c530f7/pychubby-0.2-py3-none-any.whl
.... many lines ...

Building wheels for collected packages: dlib, networkx
  Building wheel for dlib (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/pzelnip/.virtualenvs/temp/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/z9/c2zmn4_13b31g4y26q30n5c1x5hbyk/T/pip-install-3qz43g8p/dlib/setup.py'"'"'; __file__='"'"'/private/var/folders/z9/c2zmn4_13b31g4y26q30n5c1x5hbyk/T/pip-install-3qz43g8p/dlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/z9/c2zmn4_13b31g4y26q30n5c1x5hbyk/T/pip-wheel-pg9zuzb5 --python-tag cp37
       cwd: /private/var/folders/z9/c2zmn4_13b31g4y26q30n5c1x5hbyk/T/pip-install-3qz43g8p/dlib/
  Complete output (53 lines):
  running bdist_wheel
  running build
  running build_py
  package init file 'dlib/__init__.py' not found (or not a regular file)
  running build_ext
  Traceback (most recent call last):
    File "/private/var/folders/z9/c2zmn4_13b31g4y26q30n5c1x5hbyk/T/pip-install-3qz43g8p/dlib/setup.py", line 120, in get_cmake_version
      out = subprocess.check_output(['cmake', '--version'])
    File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 395, in check_output
      **kwargs).stdout
    File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 472, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
      restore_signals, start_new_session)
    File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'cmake': 'cmake'
```

There was more output, but ultimately the issue was that I didn't have `cmake` installed.  Once I installed it via Homebrew the pip install worked fine.

Should this not be documented in the Readme/docs?

**Comment by jankrepl** [comment]
Hey @pzelnip !

So as you can see in the traceback the problem occurred when trying to install a dependency`dlib` - [dlib docs](http://dlib.net/). This library is written in C++ and with bindings to Python. Since they do not provide a precompiled binary on PyPI (https://pypi.org/project/dlib/#files) you need to compile it yourself. 

Sure, we can put it in the docs  - feel free to create a pull request:)

Thank you for your feedback!

**Comment by pzelnip** [comment]
Opened #13 for this.  Thanks!
