### ISSUE TITLE
Error on performing action

### ISSUE THREAD

**Issue by liferooter** [jankrepl/pychubby#17]
# Installed software
**OS:** Arch Linux (latest)
**Python version:** 3.8.6
**Pychubby version:** 0.2
**pip version:** 20.2.4

# Steps to reproduce
1. Install `pychubby` via `pip`
2. Run `pc` (with arguments or without)
_OR_
2. Run sample script
3. Get error:
```
Traceback (most recent call last):
  File "/home/liferooter/.local/bin/pc", line 5, in <module>
    from pychubby.cli import cli
  File "/home/liferooter/.local/lib/python3.8/site-packages/pychubby/cli.py", line 8, in <module>
    import pychubby.actions
  File "/home/liferooter/.local/lib/python3.8/site-packages/pychubby/actions.py", line 14, in <module>
    from pychubby.detect import LANDMARK_NAMES, LandmarkFace, LandmarkFaces
  File "/home/liferooter/.local/lib/python3.8/site-packages/pychubby/detect.py", line 5, in <module>
    import dlib
  File "/home/liferooter/.local/lib/python3.8/site-packages/dlib/__init__.py", line 19, in <module>
    from _dlib_pybind11 import *
ImportError: /home/liferooter/.local/lib/python3.8/site-packages/_dlib_pybind11.cpython-38-x86_64-linux-gnu.so: undefined symbol: cblas_dtrsm
```
(`liferooter` is my user name)

Thank you for your help!

**Comment by liferooter** [comment]
I found that it is dlib issue. An error is thrown after import `dlib` anywhere.
